ProjectName:
  - 余少琪的框架
  -

# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
TestName: 余少琪

# 域名1
Host: https://redisdatarecall.csdn.net
# 域名2
work:

# 报告通知类型：1：钉钉 2：企业微信通知
NotificationType: 2

# 钉钉相关配置
DingTalk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=a59902a7e811f93ffe301d8326b07a2acc8aa2a864e7d61ee9fc076481ced2a6
  secret: SECdea6489dfcc3b9259da943c5ae38d3530696f2fa83ac72a9ee716e9511675b9b

# 数据库相关配置
MySqlDB:
  # 数据库开关
  switch: False
  host:
  user:
  password:
  db: test_obp_data


# 企业通知的相关配置
WeChat:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=22748687-fa3b-4e48-a5d7-0502cef422b4

email:
  send_user: 1603453211@qq.com
  email_host: smtp.qq.com
  stmp_key: rzuabbobadbuhadc
  # 收件人
  send_list: 1603453211@qq.com
